"""agregar_codigo_barras_reactivo

Revision ID: 08c41bc2e3c4
Revises: e9e4b7c1b454
Create Date: 2026-05-01 00:38:16.583285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c41bc2e3c4'
down_revision: Union[str, Sequence[str], None] = 'e9e4b7c1b454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactivos', sa.Column('codigo_barras', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_reactivos_codigo_barras'), 'reactivos', ['codigo_barras'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactivos_codigo_barras'), table_name='reactivos')
    op.drop_column('reactivos', 'codigo_barras')
    # ### end Alembic commands ###
