"""agregar_vencimiento_y_concentracion

Revision ID: 5545c8338775
Revises: 08c41bc2e3c4
Create Date: 2026-05-01 00:45:04.214845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5545c8338775'
down_revision: Union[str, Sequence[str], None] = '08c41bc2e3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactivos', sa.Column('concentracion_gl', sa.Float(), nullable=True))
    op.add_column('reactivos', sa.Column('fecha_expiracion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactivos', 'fecha_expiracion')
    op.drop_column('reactivos', 'concentracion_gl')
    # ### end Alembic commands ###
