"""Add codigo to Protocolos and Experimentos

Revision ID: 6463e1cdd6c6
Revises: 999999999999
Create Date: 2026-05-07 20:07:37.048787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6463e1cdd6c6'
down_revision: Union[str, Sequence[str], None] = '999999999999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experimentos', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_experimentos_codigo'), 'experimentos', ['codigo'], unique=True)
    op.add_column('protocolos', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_protocolos_codigo'), 'protocolos', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocolos_codigo'), table_name='protocolos')
    op.drop_column('protocolos', 'codigo')
    op.drop_index(op.f('ix_experimentos_codigo'), table_name='experimentos')
    op.drop_column('experimentos', 'codigo')
    # ### end Alembic commands ###
