"""Initial schema sync

Revision ID: 6ab2e936b665
Revises:
Create Date: 2026-04-30 08:10:11.428102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab2e936b665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('especies', 'categoria',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'especie'::character varying"))
    op.create_index(op.f('ix_especimenes_linea_id'), 'especimenes', ['linea_id'], unique=False)
    op.create_index(op.f('ix_especimenes_variegacion_id'), 'especimenes', ['variegacion_id'], unique=False)
    op.alter_column('lineas', 'metodo_propagacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'desconocido'::character varying"))
    op.drop_constraint('lineas_especie_id_nombre_key', 'lineas', type_='unique')
    op.create_index(op.f('ix_lineas_especie_id'), 'lineas', ['especie_id'], unique=False)
    op.drop_index('ix_reg_evol_especimen', table_name='registros_evolucion')
    op.drop_index('ix_reg_evol_fecha', table_name='registros_evolucion')
    op.create_index(op.f('ix_registros_evolucion_especimen_id'), 'registros_evolucion', ['especimen_id'], unique=False)
    op.create_index(op.f('ix_registros_evolucion_fecha'), 'registros_evolucion', ['fecha'], unique=False)
    op.alter_column('sustratos', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'sustrato'::character varying"))
    op.drop_constraint('variegaciones_linea_id_nombre_key', 'variegaciones', type_='unique')
    op.create_index(op.f('ix_variegaciones_linea_id'), 'variegaciones', ['linea_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variegaciones_linea_id'), table_name='variegaciones')
    op.create_unique_constraint('variegaciones_linea_id_nombre_key', 'variegaciones', ['linea_id', 'nombre'])
    op.alter_column('sustratos', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'sustrato'::character varying"))
    op.drop_index(op.f('ix_registros_evolucion_fecha'), table_name='registros_evolucion')
    op.drop_index(op.f('ix_registros_evolucion_especimen_id'), table_name='registros_evolucion')
    op.create_index('ix_reg_evol_fecha', 'registros_evolucion', ['fecha'], unique=False)
    op.create_index('ix_reg_evol_especimen', 'registros_evolucion', ['especimen_id'], unique=False)
    op.drop_index(op.f('ix_lineas_especie_id'), table_name='lineas')
    op.create_unique_constraint('lineas_especie_id_nombre_key', 'lineas', ['especie_id', 'nombre'])
    op.alter_column('lineas', 'metodo_propagacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'desconocido'::character varying"))
    op.drop_index(op.f('ix_especimenes_variegacion_id'), table_name='especimenes')
    op.drop_index(op.f('ix_especimenes_linea_id'), table_name='especimenes')
    op.alter_column('especies', 'categoria',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'especie'::character varying"))
    # ### end Alembic commands ###
