"""permitir formulacion como componente

Revision ID: e9e4b7c1b454
Revises: 6ab2e936b665
Create Date: 2026-05-01 00:27:18.686793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e4b7c1b454'
down_revision: Union[str, Sequence[str], None] = '6ab2e936b665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulacion_componentes', sa.Column('formulacion_ingrediente_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'formulacion_componentes', 'formulaciones', ['formulacion_ingrediente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'formulacion_componentes', type_='foreignkey')
    op.drop_column('formulacion_componentes', 'formulacion_ingrediente_id')
    # ### end Alembic commands ###
