"""agregar_contenedor_uid

Revision ID: fd1e1e670e91
Revises: 5545c8338775
Create Date: 2026-05-01 01:25:48.867130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1e1e670e91'
down_revision: Union[str, Sequence[str], None] = '5545c8338775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('especimenes', sa.Column('contenedor_uid', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_especimenes_contenedor_uid'), 'especimenes', ['contenedor_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_especimenes_contenedor_uid'), table_name='especimenes')
    op.drop_column('especimenes', 'contenedor_uid')
    # ### end Alembic commands ###
